version: '3.7'
services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volumes/mysql_keycloak:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: keycloak

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
        - "8181:8080"
    depends_on:
        - keycloak-mysql
    volumes:
      - ./volumes/keycloak:/opt/keycloak/data/import/

volumes:
    mysql_keycloak:
    keycloak:



